config/routes.rb
Rails.application.routes.draw do
  devise_for :applicants
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  # Write root path to login page

  root "landing_page#index" 


  resources :job_openings do
    resources :job_applications
  end

  resources :applicants do
    resources :job_applications
  end
  
  resources :job_applications do
    member do
      get :accept
      get :reject
    end
  end

  

end

app/models/applicant.rb
class Applicant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :applications
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  belongs_to :job_opening
  belongs_to :applicant
  has_one_attached :resume
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true
  validates :phone, presence: true
  validates :resume, presence: true
  validates :work_experience, presence: true
  validates :education, presence: true
  validates :address_line_1, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true 
  enum status: [:pending, :accepted, :rejected]
end

app/models/job_opening.rb
class JobOpening < ApplicationRecord
  has_many  :applications
  validates :title, presence: true , length: {minimum: 5, maximum: 35}
  validates :description, presence: true, length: { minimum: 10 }
  validates :company_name, presence: true, length: { minimum: 3, maximum: 30}
  validates :salary, presence: true, numericality: { greater_than: 0 }
  validates :location, presence: true
  validates :experience_years, presence: true, numericality: { greater_than_or_equal_to: 0 } 
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
    def new
    end    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation, :phone, :work_experience, :education, :resume_link, :address_line_1, :address_line_2, :city])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :password_confirmation])
  end

  # after signing up redirect to login page
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController

  before_action :authenticate_applicant! , only: [:new, :create]
  def index
    # Show all job applications belonging to a particular job id
    # Allow to use this method without authenticate_applicant!
    @job_applications = JobApplication.where(job_opening_id: params[:job_opening_id])
  end

  def show
    # Show a particular job application
    @job_application = JobApplication.find(params[:id])
  end

  def new
    @job_application = JobApplication.new
    @job_application.applicant_id = current_applicant.id
    @job_application.job_opening_id = params[:job_opening_id]
  end

  def create
    @job_application = JobApplication.new(job_application_params)
    # use new_applicant_job_application_path(@job_application) to create a new job application post method
    respond_to do |format|
      if @job_application.save
        format.html { redirect_to job_opening_url(@job_application.job_opening), notice: "Job application was successfully created." }
        format.json { render :show, status: :created, location: @job_application }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job_application.errors, status: :unprocessable_entity }
      end
    end
  end

  def accept
    @job_application = JobApplication.find(params[:id])
    @job_application.update_attribute(:status, "accepted")
    redirect_to job_opening_url(@job_application.job_opening), notice: "Application accepted."
  end

  def reject
    @job_application = JobApplication.find(params[:id])
    @job_application.update_attribute(:status, "rejected")
    redirect_to job_opening_url(@job_application.job_opening), notice: "Application rejected."
  end


  private
    def job_application_params
      params.require(:job_application).permit(:applicant_id, :job_opening_id, :name, :email, :phone, :resume, :work_experience, :education, :address_line_1, :address_line_2, :city, :state, :zip)
    end
end

app/controllers/job_openings_controller.rb
class JobOpeningsController < ApplicationController
  before_action :set_job_opening, only: %i[ show edit update destroy ]

  # GET /job_openings or /job_openings.json
  def index
    @job_openings = JobOpening.all
  end

  # GET /job_openings/1 or /job_openings/1.json
  def show
  end

  # GET /job_openings/new
  def new
    @job_opening = JobOpening.new
  end

  # GET /job_openings/1/edit
  def edit
  end

  # POST /job_openings or /job_openings.json
  def create
    @job_opening = JobOpening.new(job_opening_params)

    respond_to do |format|
      if @job_opening.save
        format.html { redirect_to job_opening_url(@job_opening), notice: "Job opening was successfully created." }
        format.json { render :show, status: :created, location: @job_opening }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job_opening.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_openings/1 or /job_openings/1.json
  def update
    respond_to do |format|
      if @job_opening.update(job_opening_params)
        format.html { redirect_to job_opening_url(@job_opening), notice: "Job opening was successfully updated." }
        format.json { render :show, status: :ok, location: @job_opening }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job_opening.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_openings/1 or /job_openings/1.json
  def destroy
    @job_opening.destroy

    respond_to do |format|
      format.html { redirect_to job_openings_url, notice: "Job opening was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_opening
      @job_opening = JobOpening.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_opening_params
      params.require(:job_opening).permit(:title, :description, :company_name, :salary, :location, :education_requirements, :experience_years, :skills)
    end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def index
  end
end

app/helpers/applicant_helper.rb
module ApplicantHelper
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/job_applications_helper.rb
module JobApplicationsHelper
end

app/helpers/job_openings_helper.rb
module JobOpeningsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/views/job_applications/_form.html.erb
<%= form_with model: job_application, url: job_opening_job_applications_path(@job_application.job_opening_id) do |form| %>
    <%= form.hidden_field :applicant_id, value: current_applicant.id%>
    <%= form.hidden_field :job_opening_id, value: @job_application.job_opening_id %>
    <%= form.hidden_field :email, value: current_applicant.email %> 

    <div>
        <%= form.label :name, style: "display: block" %>
        <%= form.text_field :name %>
    </div>

    <%if job_application.errors[:name].any? %>
        <div style="color: red;
    display: flex;
    margin-top: -17px;
    margin-bottom: -20px;
    margin-left: -54px;">
            <ul>
                <% job_application.errors[:name].each do |error| %>
                <li><%= error %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div>
        <%= form.label :phone, style: "display: block" %>
        <%= form.text_field :phone %>
    </div>
    
    <%if job_application.errors[:phone].any? %>
        <div style="color: red;
    display: flex;
    margin-top: -17px;
    margin-bottom: -20px;
    margin-left: -54px;">
            <ul>
                <% job_application.errors[:phone].each do |error| %>
                <li><%= error %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
     
    <div class="field">
        <%= form.label :address_line_1, style: "display: block" %>
        <%= form.text_field :address_line_1 %>
    </div>

    <%if job_application.errors[:address_line_1].any?%>
        <div style="color: red;
        display: flex;
        margin-top: -17px;
        margin-bottom: -20px;
        margin-left: -54px;">
            <ul>
                <% job_application.errors[:address_line_1].each do |error| %>
                <li><%= error %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :address_line_2, style: "display: block" %>
        <%= form.text_field :address_line_2 %>
    </div>

    <div class="field">
        <%= form.label :city, style: "display: block" %>
        <%= form.text_field :city %>
    </div>

    <%if job_application.errors[:city].any?%>
        <div style="color: red;
        display: flex;
        margin-top: -17px;
        margin-bottom: -20px;
        margin-left: -54px;">
            <ul>
                <% job_application.errors[:city].each do |error| %>
                <li><%= error %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :state, style: "display: block" %>
        <%= form.text_field :state %>
    </div>

    <%if job_application.errors[:state].any?%>
        <div style="color: red;
        display: flex;
        margin-top: -17px;
        margin-bottom: -20px;
        margin-left: -54px;">
            <ul>
                <% job_application.errors[:state].each do |error| %>
                <li><%= error %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :zip, style: "display: block" %>
        <%= form.text_field :zip %>
    </div>

    <%if job_application.errors[:zip].any?%>
        <div style="color: red;
        display: flex;
        margin-top: -17px;
        margin-bottom: -20px;
        margin-left: -54px;">
            <ul>
                <% job_application.errors[:zip].each do |error| %>
                <li><%= error %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :education, style: "display: block" %>
        <%= form.text_field :education %>
    </div>

    <%if job_application.errors[:education].any?%>
        <div style="color: red;
        display: flex;
        margin-top: -17px;
        margin-bottom: -20px;
        margin-left: -54px;">
            <ul>
                <% job_application.errors[:education].each do |error| %>
                <li><%= error %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :work_experience, style: "display: block" %>
        <%= form.text_area :work_experience %>
    </div>

    <%if job_application.errors[:work_experience].any?%>
        <div style="color: red;
        display: flex;
        margin-top: -17px;
        margin-bottom: -20px;
        margin-left: -54px;">
            <ul>
                <% job_application.errors[:work_experience].each do |error| %>
                <li><%= error %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field" style="
        display: flex;
        flex-direction: column;
        /* padding-left: 17px; */
        /* margin-left: 100px; */
        width: 184px;
    ">
        <%= form.label :resume, style: "display: block" %>
        <%= form.file_field :resume%>
    </div>

    <%if job_application.errors[:resume].any?%>
        <div style="color: red;
        display: flex;
        margin-top: -17px;
        margin-bottom: -20px;
        margin-left: -54px;">
            <ul>
                <% job_application.errors[:resume].each do |error| %>
                <li><%= error %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/job_applications/_job_application.html.erb
<%stylesheet_link_tag "job_applications_show" ,"data-turbo-track": "reload"%>
<div id="<%= dom_id job_application %>" class="applicationdetails">

<p>
    <strong>Name :</strong>
    <%= job_application.name %>
</p>    

<p>
    <strong>Email :</strong>
    <%= job_application.email %>
</p>

<p>
    <strong>Phone :</strong>
    <%= job_application.phone %>
</p>

<p>
    <strong>Work Experience:</strong>
    <%= job_application.work_experience %>
</p>

<p>
    <strong>Education:</strong>
    <%= job_application.education %>
</p>

<p>
    <strong>Address Line 1:</strong>
    <%= job_application.address_line_1 %>
</p>

<p>
    <strong>Address Line 2:</strong>
    <%= job_application.address_line_2 %>
</p>

<p>
    <strong>City:</strong>
    <%= job_application.city %>
</p>

<p>
    <strong>State:</strong>
    <%= job_application.state %>
</p>

<p>
    <strong>Zip Code:</strong>
    <%= job_application.zip %>
</p>

<p style="display: flex;
    flex-direction: column;
    row-gap: 10px;">
    <strong>Resume :</strong>
    <embed src = "<%= url_for(job_application.resume) %>" width = "500" height = "350" type = 'application/pdf' />
</p>

</div>

app/views/job_applications/index.html.erb
<p style="color: green"><%= notice %></p>
<%stylesheet_link_tag "job_applications_index" ,"data-turbo-track": "reload"%>
<h1 style="display: flex; justify-content: center; font-family: monospace; font-size: 30px; margin-top: 20px; margin-bottom: 20px;"> Job Applications </h1>

<% if @job_applications.empty? %>
  <p>No job applications</p>
<% else %>
<div id = "job_applications">
    <% @job_applications.each do |job_application| %>
        <p>
        <strong style="font-family: monospace;font-size: 18px;display :flex;justify-content: center;">Job Application Id: <%=job_application.id%></strong><br/>
        <%= job_application.name %> applied for <%= job_application.job_opening.title %> at <%= job_application.job_opening.company_name %> , <%= job_application.job_opening.location %>
        </p>
        <%# Add accept and reject buttons %>
        <p>
            <button>
            <%= link_to "Show application", job_opening_job_application_path(job_application.job_opening_id, job_application.id) %>
            </button>
        </p>

    <% end %>
</div> 
<% end %>

app/views/job_applications/new.html.erb
<h1 style = "text-align: center; margin-top: 50px; margin-bottom: 50px;">Apply for the job opening</h1>

<%= render "form", job_application: @job_application %>

<br>

<div style = "text-align: center;
    margin-top: 50px;
    margin-bottom: 50px;
    box-shadow: rgb(0 0 0 / 24%) 0px 3px 8px;
    width: fit-content;
    margin-left: auto;
    margin-right: auto;
    padding: 13px;
    text-transform: uppercase;
    border-radius: 6px;
    background-color: aliceblue;
    text-decoration: none;" >
  <%= link_to "Back to job openings", job_openings_path %>
</div>

app/views/job_applications/show.html.erb
<p style="color: green"><%= notice %></p>
<% stylesheet_link_tag "job_applications_show" ,"data-turbo-track": "reload"%>
<%= render @job_application %>

<div class="applicationbuttons">
    <%# Define accept and reject buttons here %>
    <button>
    <%= link_to "Back to job applications" , job_opening_job_applications_path(@job_application.job_opening_id) %>
    </button>
    <button style="background-color: greenyellow;">
        <%# link to job_applications/id/accept %>
        <%= link_to "Accept", accept_job_application_path(@job_application.id) %>
    </button>
    <button style="background-color: orangered;">
        <%# link to job_applications/id/reject %>
        <%= link_to "Reject", reject_job_application_path(@job_application.id) %>
    </button>
</div>

app/views/job_openings/_form.html.erb
<%= form_with(model: job_opening) do |form| %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <%if job_opening.errors[:title].any? %>
        <div style="color: red;
    display: flex;
    margin-top: -17px;
    margin-bottom: -14px;
    margin-left: 10px;">
            <ul>
                <% job_opening.errors[:title].each do |error| %>
                <li><%= error %></li>
                <% end %>
            </ul>
        </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <%if job_opening.errors[:description].any? %>
        <div style="color: red;
    display: flex;
    margin-top: -17px;
    margin-bottom: -14px;
    margin-left: 10px;">
            <ul>
                <% job_opening.errors[:description].each do |error| %>
                <li><%= error %></li>
                <% end %>
            </ul>
        </div>
  <% end %>

  <div>
    <%= form.label :company_name, style: "display: block" %>
    <%= form.text_field :company_name %>
  </div>

  <%if job_opening.errors[:company_name].any? %>
        <div style="color: red;
    display: flex;
    margin-top: -17px;
    margin-bottom: -14px;
    margin-left: 10px;">
            <ul>
                <% job_opening.errors[:company_name].each do |error| %>
                <li><%= error %></li>
                <% end %>
            </ul>
        </div>
  <% end %>

  <div>
    <%= form.label :salary, style: "display: block" %>
    <%= form.number_field :salary %>
  </div>

  <%if job_opening.errors[:salary].any? %>
        <div style="color: red;
    display: flex;
    margin-top: -17px;
    margin-bottom: -14px;
        margin-left: -120px;">
            <ul>
                <% job_opening.errors[:salary].each do |error| %>
                <li><%= error %></li>
                <% end %>
            </ul>
        </div>
  <% end %>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <%if job_opening.errors[:location].any? %>
        <div style="color: red;
    display: flex;
    margin-top: -17px;
    margin-bottom: -14px;
    margin-left: -120px;">
            <ul>
                <% job_opening.errors[:location].each do |error| %>
                <li><%= error %></li>
                <% end %>
            </ul>
        </div>
  <% end %>

  <div>
    <%= form.label :education_requirements, style: "display: block" %>
    <%= form.text_field :education_requirements %>
  </div>

    
  <div>
    <%= form.label :experience_years, style: "display: block" %>
    <%= form.number_field :experience_years %>
  </div>

  <%if job_opening.errors[:experience_years].any? %>
        <div style="color: red;
    display: flex;
    margin-top: -17px;
    margin-bottom: -14px;
    margin-left: -120px;">
            <ul>
                <% job_opening.errors[:experience_years].each do |error| %>
                <li><%= error %></li>
                <% end %>
            </ul>
        </div>
  <% end %>

  <div>
    <%= form.label :skills, style: "display: block" %>
    <%= form.text_field :skills %>
  </div>

  <%if job_opening.errors[:skills].any? %>
        <div style="color: red;
    display: flex;
    margin-top: -17px;
    margin-bottom: -14px;
    margin-left: -120px;">
            <ul>
                <% job_opening.errors[:skills].each do |error| %>
                <li><%= error %></li>
                <% end %>
            </ul>
        </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/job_openings/_job_opening.html.erb
<% stylesheet_link_tag "job_opening_show" ,"data-turbo-track": "reload"%>
<div id="<%= dom_id job_opening %>" class="jobcard">
  <p>
    <strong>Title:</strong>
    <%= job_opening.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= job_opening.description %>
  </p>

  <p>
    <strong>Company name:</strong>
    <%= job_opening.company_name %>
  </p>

  <p>
    <strong>Salary:</strong>
    <%= job_opening.salary %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= job_opening.location %>
  </p>

  <p>
    <strong>Education requirements:</strong>
    <%= job_opening.education_requirements %>
  </p>

  <p>
    <strong>Experience years:</strong>
    <%= job_opening.experience_years %>
  </p>

  <p>
    <strong>Skills:</strong>
    <%= job_opening.skills %>
  </p>

</div>

app/views/job_openings/edit.html.erb
<h1 style="display: flex; justify-content: center; font-family: monospace; font-size: 30px; margin-top: 20px; margin-bottom: 20px;">Editing job opening</h1>

<%= render "form", job_opening: @job_opening %>
<% stylesheet_link_tag "job_opening_show" ,"data-turbo-track": "reload"%>
<br>

<div class="adminbuttons">
<button>
  <%= link_to "Show this job opening", @job_opening %>
</button>
<button>
  <%= link_to "Back to job openings", job_openings_path %>
</button>
</div>

app/views/job_openings/index.html.erb
<p style="color: green"><%= notice %></p>
<%stylesheet_link_tag "job_opening_index" ,"data-turbo-track": "reload"%>
<%# Is job opening is empty show no job opening else render all job openings %>

<h1 class="jobopeninghead">Job openings</h1>
<% if @job_openings.empty? %>
  <p>No job openings</p>
<% else %>
  <div id="job_openings">
    <% @job_openings.each do |job_opening| %>
      <p>
        <strong style ="font-family: monospace;
    font-size: 18px;">Job Opening:</strong>
        <%= job_opening.title %> at <%= job_opening.company_name %>
      </p>
      <p class="showlink">
        <%= link_to "Show opening", job_opening %>
      </p>
    <% end %>
  </div>
<% end %>
<%# Show new job opening when applicant is not signed in %>
<% if applicant_signed_in? %>
  <p>
  </p>
<%else%>
  <button class="newjobbutton">
    <%= link_to "New job opening", new_job_opening_path %>
  </button>
<% end %>

app/views/job_openings/new.html.erb
<h1 style="display: flex; justify-content: center; font-family: monospace; font-size: 30px; margin-top: 20px; margin-bottom: 20px;">New job opening</h1>

<%= render "form", job_opening: @job_opening %>

<br>

<button style="padding: 16px;
    font-family: monospace;
    font-size: 15px;
    text-transform: uppercase;
    font-weight: 900;
    background-color: cornflowerblue;
    border-radius: 14px;
    border-color: transparent;
    display: flex;
    margin-left: auto;
    margin-right: auto;">
  <%= link_to "Back to job openings", job_openings_path %>
</button>

app/views/job_openings/show.html.erb
<p style="color: green"><%= notice %></p>
<% stylesheet_link_tag "job_opening_show" ,"data-turbo-track": "reload"%>
<%= render @job_opening %>

<%# Show option for apply when i am logged in and option for edit and destroy when i am not logged in %>
<% if applicant_signed_in? %>
  <div class ="applicant_buttons">
  <button>
    <%= link_to "Apply", new_applicant_job_application_path(current_applicant, job_opening_id: @job_opening.id) %>
  </button>
  <button>
    <%= link_to "Back to openings", job_openings_path %>
  </button>
  </div>
<% else %>
  <div class="adminbuttons">
  <button>
  <%= link_to "Edit this job opening", edit_job_opening_path(@job_opening) %>
  </button>
  <button>
  <%= link_to "Back to job openings", job_openings_path %> 
  </button>
  <button>
  <%= link_to "Destroy this job opening", @job_opening, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  </button>
  <%# Write a link to show all applications of this particular jobid %>
  <button>
  <%= link_to "Show all applications for this job opening", job_opening_job_applications_path(@job_opening) %>
  </button>
  </div>
<% end %>

app/views/landing_page/index.html.erb
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

<div class="landing_top">
    <div class="landing_top_left">
          <h1>Find your dream job</h1>
          <p>Lorem ipsum dolor sit amet. At rerum neque sit facilis enim et minus sint qui sunt voluptatem? Qui quod labore sit dicta tempora rem pariatur rerum hic consequatur facere et doloribus corrupti.<br/>
          Et quidem tempore est voluptates beatae sed veritatis impedit ut labore sequi aut beatae dolor et similique delectus sed repellendus praesentium! Ut sapiente necessitatibus sed dolor necessitatibus qui optio incidunt non placeat iure ut perspiciatis error!<br/>
          At rerum doloremque nam commodi quia qui saepe consectetur non ducimus eaque et suscipit voluptatibus rem nisi excepturi vel dolorem saepe. Est nesciunt voluptatum aut porro laboriosam a consequatur optio a ullam tempore qui aliquid officiis!</p>
      </div>
      <%# Add landing.png here %>
    <%= image_tag("landing.png") %>
</div>

<div class="landing_middle" style="display: flex;
    flex-direction: column;
    justify-content: center;
    margin-top: 60px;">
    <div class="landing_middle_top" style="display: flex;
    flex-direction: column;
    justify-content: center;">
        <h1 style="text-align: center;
    font-family: monospace;"
        > Browse Categories </h1>
        <p style="margin-top: 15px;
    font-family: math;
    font-size: 15px;
    color: gray;
    margin-left: auto;
    margin-right: auto;
    "> Most popular categories of portal , sorted by popularity </p>
    </div>
    <div class="landing_middle_bottom" style="display: flex;
    justify-content: center;
    flex-wrap: wrap;
    padding-left: 212px;
    padding-right: 175px;
    column-gap: 32px;
    row-gap: 28px;
    ">
        <div class="imgcard">
            <%=image_tag("finance.png" , style: "width: 170px;height: 150px;")%>
            <p class="imgcard_heading"> Finance </p>
            <p class="imgcard_text"> (4286 jobs) </p>
        </div>
        <div class="imgcard">
            <%=image_tag("sales.png" , style: "width: 170px;height: 150px;")%>
            <p class="imgcard_heading"> Sales/Marketing </p>
            <p class="imgcard_text"> (2000 jobs) </p>
        </div>
        <div class="imgcard">
            <%=image_tag("education.png" , style: "width: 170px;height: 150px;")%>
            <p class="imgcard_heading"> Education/Training </p>
            <p class="imgcard_text"> (1450 jobs) </p>
        </div>
        <div class="imgcard">
            <%=image_tag("technologies.png" , style: "width: 170px;height: 150px;")%>
            <p class="imgcard_heading"> Technologies </p>
            <p class="imgcard_text"> (5100 jobs) </p>
        </div>
        <div class="imgcard">
            <%=image_tag("art.png" , style: "width: 170px;height: 150px;")%>
            <p class="imgcard_heading"> Art/Design </p>
            <p class="imgcard_text"> (5079 jobs) </p>
        </div>
        <div class="imgcard">
            <%=image_tag("healthcare.png" , style: "width: 170px;height: 150px;")%>
            <p class="imgcard_heading"> Healthcare </p>
            <p class="imgcard_text"> (3235 jobs) </p>
        </div>
        <div class="imgcard">
            <%=image_tag("science.png" , style: "width: 170px;height: 150px;")%>
            <p class="imgcard_heading"> Science </p>
            <p class="imgcard_text"> (1800 jobs) </p>
        </div>
        <div class="imgcard">
            <%=image_tag("food.png" , style: "width: 170px;height: 150px;")%>
            <p class="imgcard_heading"> Food Services </p>
            <p class="imgcard_text"> (4286 jobs) </p>
        </div>
    </div>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobportal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <nav>
    <div style="
    display: flex;
    margin-right: auto;
    margin-left: 19px;">
    <%# Set the height and width of the image inside the embedded ruby tag %>
    <%= image_tag("joblogo1.svg", :height => '36', :width => '37') %>
    </div>
    <% if applicant_signed_in? %>
      <%= link_to "Home", root_path %>
      <%= link_to "Job openings", job_openings_path %>
      <%= link_to "Sign out", destroy_applicant_session_path, method: :delete%>
    <% else %>
      <%= link_to "Home", root_path %>
      <%= link_to "Sign in", new_applicant_session_path %>
    <% end %>
  </nav>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>